# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(1F2228)
$foreground = rgb(F3E3DC)
$color0 = rgb(45484F)
$color1 = rgb(12496F)
$color2 = rgb(654657)
$color3 = rgb(694A59)
$color4 = rgb(3D708A)
$color5 = rgb(8E6D69)
$color6 = rgb(A68474)
$color7 = rgb(E6CFC4)
$color8 = rgb(A19189)
$color9 = rgb(176194)
$color10 = rgb(875D74)
$color11 = rgb(8C6276)
$color12 = rgb(5195B8)
$color13 = rgb(BD918C)
$color14 = rgb(DDB09A)
$color15 = rgb(E6CFC4)
