# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #F3E3DC
background         #1F2228
cursor             #BDA0A8

active_tab_foreground     #1F2228
active_tab_background     #F3E3DC
inactive_tab_foreground   #F3E3DC
inactive_tab_background   #1F2228

active_border_color   #F3E3DC
inactive_border_color #1F2228
bell_border_color     #12496F

color0      #45484F
color1		#12496F
color2		#654657
color3		#694A59
color4		#3D708A
color5		#8E6D69
color6		#A68474
color7		#E6CFC4
color8		#A19189
color9		#176194
color10		#875D74
color11		#8C6276
color12		#5195B8
color13		#BD918C
color14		#DDB09A
color15		#E6CFC4
