font=Maple Mono NF CN:size=14

# 是否感知高 DPI
# dpi-aware=yes

[scrollback]
lines=100000

[main]
include=~/.config/foot/themes/noctalia

[colors-dark]
alpha=0.8
# blur=yes

# URL 颜色
urls=4fd6be

# flash（快速闪现选区/查找）
flash=7f7f00
flash-alpha=0.5

dim-blend-towards=black
# dim-opacity=0.25   # 如果你经常用 tmux/screen，可以打开

# 256色扩展
16=ff966c
17=c53b53

[url]
launch=firefox ${url}

[key-bindings]
scrollback-up-half-page=Control+k
scrollback-down-half-page=Control+j

show-urls-launch=Control+Shift+b
show-urls-copy=Control+Shift+y

search-start=Control+Shift+f

spawn-terminal=Control+Shift+n

